from enum import Enum


class EventType(str, Enum):
    TRADE_SIGNAL = "TRADE_SIGNAL"
    TASK_SCHEDULED = "TASK_SCHEDULED"
    AUTOMATION_TRIGGERED = "AUTOMATION_TRIGGERED"
    NOTE_CREATED = "NOTE_CREATED"
    SYSTEM_HEALTH_CHECK = "SYSTEM_HEALTH_CHECK"